name: Feature Request
description: Propose a new capability or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Describe the user/business problem first, then propose the smallest viable solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are we solving?
      placeholder: As a teller/supervisor, I need ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What should we implement?
      placeholder: Minimal implementation details and expected behavior.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Other approaches and why they were not selected.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Testable outcomes.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: input
    id: docs
    attributes:
      label: Related Docs/Spec
      description: Link any relevant docs in /docs
      placeholder: docs/10_phase1_spec.md
